version: "3.8"

services:
  bot:
    build: .
    container_name: vanileautoposter-bot
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=vanileuser
      - DB_PASSWORD=vanilepass
      - DB_NAME=vaniledb
    volumes:
      - .:/app
    restart: unless-stopped

  mariadb:
    image: mariadb:11.3
    container_name: vanileautoposter-db
    environment:
      - MARIADB_ROOT_PASSWORD=rootpass
      - MARIADB_DATABASE=vaniledb
      - MARIADB_USER=vanileuser
      - MARIADB_PASSWORD=vanilepass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: vanileautoposter-phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=vanileuser
      - PMA_PASSWORD=vanilepass
    ports:
      - "8085:80"
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  mariadb_data:
